#! /bin/bash

# this script generates the upload files for DOWNLOAD.COM
# call this file as "hexxfer FileToAdd [UserNumber [o]]"
# depends on: hexdump(util-linux), awk(gawk) & printf(coreutils)

if [ "x$1" != "x" ] && [ -f $1 ]; then
  OUTFILE="~/upload/pkgFile.txt"
  INFILE=$(basename $1)
  PADD=""
  if [ "x$2" = "x" ]; then
    USER="0"
  else
    printf -v USER "%X" $2
  fi
  if [ -e $OUTFILE ]; then
    if [ "x$3" = "xo" ]; then
      rm $OUTFILE
    else
      PADD="  "
    fi
  fi
  echo -ne "A:DOWNLOAD "$INFILE"\x0d\x0a"$PADD"U"$USER"\x0d\x0a:" >> $OUTFILE
  COUNT=0
  SUM=0
  for BYTE in `hexdump -Cv $1 | awk -F '  ' '{ print toupper($2 " " $3) }'`; do
    SUM=$(( SUM + 0x$BYTE ))
    COUNT=$(( COUNT + 1 ))
    echo -n $BYTE >> $OUTFILE
  done
  printf -v C "0%X" $COUNT 
  printf -v S "0%X" $SUM
  echo -ne '>'${C: -2}${S: -2}"\x0d\x0a" >> $OUTFILE
else
  echo "no file $1"
fi
