; TESTCODE.ASM
; Douglas Gilliland 2022
;
; Read a char from VDU/ACIA, write a char to VDU/ACIA
; Load in MIKBUG (SmithBug) using & command
;
; Run toolchain in DOS window - assembler
;	..\a68.exe TESTCODE.ASM -l TESTCODE.LST -s TESTCODE.s
; To make a hex file that can be loaded
;	..\srec_cat TESTCODE.s -offset - -minimum-addr TESTCODE.s -o TESTCODE.hex -Intel

ACIACS	EQU	$FC18
ACIADA	EQU	$FC19
;
START	
			ORG	$0000
LBACK
		BSR		GETCHAR
		BSR		OUTCHAR
		JMP		LBACK
;
GETCHAR	PSHB
WAITIN	LDAB	ACIACS	; LOAD ACIA CONTROL REGISTER
		ASRB			; SHIFT RIGHT  ACIADA
		BCC 	WAITIN	; IF CARRY NOT SET THEN AGAIN
		LDAA 	ACIADA	; LOAD DATA REGISTER
		PULB			; RESTORE B REGISTER
		RTS
;
OUTCHAR	PSHB			; SAVE B
WAITOUT	LDAB	ACIACS	; LOAD ACIA CONTROL REGISTER
		ASRB			; SHIFT RIGHT
		ASRB			; SHIFT RIGHT
		BCC 	WAITOUT	; IF CARRY NOT SET DO AGAIN
		STAA 	ACIADA	; SEND CHARACTOR TO ACIA
		PULB			; RESTORE B
		RTS				; RETURN FROM ROUTINE

		END
		