; TESTCODE.ASM
; a68 TESTCODE.ASM -l TESTCODE.LST -s TESTCODE.s
; srec_cat TESTCODE.s -offset - -minimum-addr TESTCODE.s -o TESTCODE.hex -Intel

ACIACS	EQU	$FC18
ACIADA	EQU	$FC19
;
START	
			ORG	$0000
LBACK
		BSR		GETCHAR
		BSR		OUTPUTA
		JMP		LBACK
;
GETCHAR	PSHB
WAITIN	LDAB	ACIACS	; LOAD ACIA CONTROL REGISTER
		ASRB			; SHIFT RIGHT  ACIADA
		BCC 	WAITIN	; IF CARRY NOT SET THEN AGAIN
		LDAA 	ACIADA	; LOAD DATA REGISTER
		PULB			; RESTORE B REGISTER
		RTS
;
OUTPUTA	PSHB			; SAVE B
WAITOUT	LDAB	ACIACS	; LOAD ACIA CONTROL REGISTER
		ASRB			; SHIFT RIGHT
		ASRB			; SHIFT RIGHT
		BCC 	WAITOUT	; IF CARRY NOT SET DO AGAIN
		STAA 	ACIADA	; SEND CHARACTOR TO ACIA
		PULB			; RESTORE B
		RTS				; RETURN FROM ROUTINE

		END
		