-- ---------------------------------------
-- Table generated by pyCSVtoROM.py script
-- MIT v3 license
-- Written by Land Boards, LLC, 2019
-- ---------------------------------------

library ieee;
	use ieee.std_logic_1164.all;
	use ieee.numeric_std.all;
	use ieee.std_logic_unsigned.all;

ENTITY RomTable IS
	PORT
	(
		address : in std_logic_vector(6 downto 0);
		q : out std_logic_vector(6 downto 0)
	);
END RomTable;

architecture behavior of RomTable is
type romtable is array (0 to 127) of std_logic_vector(6 downto 0);
constant romdata : romtable :=
(
x"40",x"43",x"46",x"49",x"4C",x"4F",x"52",x"55",x"58",x"5B",x"5E",x"60",x"63",x"66",x"68",x"6A",
x"6D",x"6F",x"71",x"73",x"75",x"76",x"78",x"79",x"7A",x"7B",x"7C",x"7D",x"7E",x"7E",x"7F",x"7F",
x"7F",x"7F",x"7F",x"7E",x"7E",x"7D",x"7C",x"7B",x"7A",x"78",x"77",x"75",x"74",x"72",x"70",x"6E",
x"6C",x"69",x"67",x"64",x"62",x"5F",x"5C",x"59",x"57",x"54",x"51",x"4E",x"4A",x"47",x"44",x"41",
x"3E",x"3B",x"38",x"35",x"31",x"2E",x"2B",x"28",x"26",x"23",x"20",x"1D",x"1B",x"18",x"16",x"13",
x"11",x"F",x"D",x"B",x"A",x"8",x"7",x"5",x"4",x"3",x"2",x"1",x"1",x"0",x"0",x"0",
x"0",x"0",x"1",x"1",x"2",x"3",x"4",x"5",x"6",x"7",x"9",x"A",x"C",x"E",x"10",x"12",
x"15",x"17",x"19",x"1C",x"1F",x"21",x"24",x"27",x"2A",x"2D",x"30",x"33",x"36",x"39",x"3C",x"40"
);
