* TEST MULTICOMP TIMER INTERRUPT FROM CAMELFORTH
*
* 1/ NEED CAMELFORTH RUNNING FROM RAM SO THAT WE CAN CHANGE THE
* INTERRUPT VECTOR:
*    HEX MMUMAP EFTOCD E000 C000 2000 CMOVE CDTOCD PIVOTRST
* 2/ CHANGE VECTOR AT FFF8 TO POINT TO ISR
*    HEX 100F FFF8 !
* 3/ ENTER THIS CODE BELOW TO RAM @1000 (USE THE .LST FILE)
*    eg: 3606 1000 ! 8602 1002 ! (etc)
* 4/ RUN IT:
*    HEX 1000 EXECUTE
*
* SHOULD RETURN TO THE CAMELFORTH PROMPT IMMEDIATELY.
* INSPECT LOCATION "COUNT" - SHOULD SEE IT INCREMENTING AT 50Hz
* WRISTWATCH TEST: I SAW IT INCREMENT FROM 2665 TO 5679 IN
* 60s. (5679-2665)/50 = 60.28s

TIMER   EQU  $FFDD

        ORG $1000

* COME HERE FROM FORTH SO MUST PRESERVE FORTH VM: Y, D
* ENABLE TIMER AND INTERRUPT
         PSHU D
         LDA #2
         STA TIMER              START TIMER
         ANDCC #%11101111       ENABLE INTERRUPTS
         PULU D
* RETURN TO CAMELFORTH
         PULU Y
         JMP [,Y++]


* ISR - ALL REGISTERS SAVED/RESTORED ACROSS HERE
ISR     INC TIMER
        BPL NOTME
        LDX COUNT
        LEAX 1,X            aka INX
        STX COUNT
NOTME
        RTI

COUNT   FDB $0
