#!/bin/bash
#
# assumes as9 srec_cat and (PERL scripts) hex2bin hex_addr_remap are on $PATH

# memory-resident debug monitor
NAME=kipper1_buggy.asm
BASE=`basename -s asm $NAME`
as9 $NAME -l s19 now
srec_cat ${BASE}s19 -Output ${BASE}hex -Intel -Data-Only -address-length=2
##hex2bin ${BASE}hex > ${BASE}bin


# concatenate with FORTH image to form ROM image
cat kipper1_buggy.hex 6809K.HEX > kipper1.hex

# re-base the addresses from $C000 to $0000 for EPROM programmer
hex_addr_remap c000 kipper1.hex > kipper1_rom.hex
